imports:
  - { resource: "adapters.yml" }
  - { resource: "migration.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
  
  aPajo\MultiTenancyBundle\Service\:
    resource: '../../Service/*'
  
  aPajo\MultiTenancyBundle\Service\Resolver\HostBasedResolver:
    arguments:
      $requestStack: '@request_stack'
      $tokenstorage: '@security.untracked_token_storage'

  aPajo\MultiTenancyBundle\Event\Listener\RequestListener:
